(assert-exception AssertionException (let (('x 2)) x))